### ISSUE TITLE
Build fails under alpine Linux (w/musl libc)

### ISSUE THREAD

**Issue by rhowe-gds** [RuntimeTools/omr-agentcore#90]
Observed when building appmetrics under alpine 3.10.1: https://github.com/RuntimeTools/appmetrics/issues/454#issuecomment-511137895

```
../omr-agentcore/src/ibmras/common/port/linux/Thread.cpp: In function 'void ibmras::common::port::stopAllThreads()':
../omr-agentcore/src/ibmras/common/port/linux/Thread.cpp:144:8: error: 'pthread_getname_np' was not declared in this scope
   rc = pthread_getname_np(top, theName, 16);
        ^~~~~~~~~~~~~~~~~~
```

Introduced by commit https://github.com/RuntimeTools/omr-agentcore/commit/7b11cfe5a7526acb022388fc04148b788ab6ef7d, but `pthread_getname_np` is not available in musl libc (only setname)

Reproducible by adding this `Dockerfile`
```
FROM alpine:3.10.1

RUN ["apk", "add", "--no-cache", "make", "g++"]

ADD . /omr-agentcore

ENV BUILD=xa64

WORKDIR /omr-agentcore

RUN ["make"]
```
and running `docker build .`

**Comment by robolivable** [comment]
Quite a coincidence! I've been working on getting this exact issue resolved in the past couple of days. My temporary work around just for getting a POC up is actually going ahead and [implementing the pthread_getname_np method in musl](https://github.com/robolivable/musl/commit/8a39ea9e6b51367e15a6747f85c1fa37a3a5c213). Building these as separate binaries from source, and pointing the `binding.gyp` file to the includes/libs does the trick for now...

I wonder about the need for this method in the first place... maybe there's an alternative for the commit that introduced its use?

**Comment by rhowe-gds** [comment]
I _think_ it's only used for monitoring the JVM and therefore isn't needed at all for appmetrics. I can't see how else you could identify a particular thread although maybe the way to do it is to keep a reference to all the threads we create and use that list when stopping them?

**Comment by robolivable** [comment]
Maybe, but it seems like we only care about [identifying a particular thread](https://github.com/RuntimeTools/omr-agentcore/commit/7b11cfe5a7526acb022388fc04148b788ab6ef7d#diff-4f122f453bb01e5ef9fdaa60893d8b05R147). I just wonder if its name is its only identifier.

**Comment by frostmar** [comment]
I've run into this problem when trying to use the appmetrics nodejs package in an Alpine Linux docker image.
`npm install appmetrics` fails with the C compiler error above.

FWIW, it seems like msul is considering supporting `pthread_getname_np` 
A search turns up this on the msul developer mailing list archive from July 2019:
https://www.openwall.com/lists/musl/2019/07/17/3
> > On Wed, Jul 17, 2019 at 12:20:09AM -0400, Robert Oliveira wrote:
> > I'm simply curious about the absence of a pthread getter method
> > (phtread_getname_np) in musl, since it seems the setter method
> > (pthread_setname_np) has been around for a while. This only came up because
> > of a reference to this method in a NodeJS library that uses some cpp
> > bindings (when using an Alpine image for running Node).
> > 
> > Here's a relevant Github link regarding the matter, for what it's worth:
> > https://github.com/RuntimeTools/omr-agentcore/issues/90
> > 
> > Thanks in advance for your time.
> 
> It's come up before, and there were reasons for not doing it, but not
> terribly compelling ones. I promised to look at it again this release
> cycle and I suspect that'll end with it getting added.
> Rich

**Comment by mattcolegate** [comment]
OK everyone, been a while coming but I've sorted out our problems with Alpine and you're good to go on this.
Omr agentcore 4.0.5, Appmetrics 5.0.5, also available on npm.
I tested using this `Dockerfile`:
```
FROM node:alpine

RUN ["apk", "add", "--no-cache", "make", "g++", "python", "git"]

RUN ["npm", "install", "appmetrics"]

WORKDIR node_modules/appmetrics

RUN ["npm", "install"]

RUN ["npm", "test"]
```
Open new issues if you have any :-)
